# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IndiaSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'MBProgressHUD'
 pod 'IQKeyboardManagerSwift'
  # Pods for IndiaSwift
   pod 'Firebase/Core'
   pod 'Firebase/Messaging'
  target 'IndiaSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IndiaSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
